server:
  port: 8455
logging:
  file: /java/C2S_LOGS/pep/pep.log
info:
  component: PEP Core Service

#TODO: until finding a better solution, disable hystrix command timeout. See https://github.com/spring-cloud/spring-cloud-netflix/issues/321#issuecomment-97727313
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ReadTimeout: 50000
security:
  oauth2:
    client:
      client-id: pep
---
# enables ssl and adds /pep context path when activated
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /pep
---
# updates configuration for docker environment
spring.profiles: docker
